#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=1G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
chmod -R u+rwX,g+rwX,o+r $install_dir/lichen-markdown/src

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

# Create a dedicated PHP-FPM config
ynh_app_setting_set_default --key="php_upload_max_filesize" --value="1G"
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================

#htpasswd -cb $install_dir/lichen-markdown/.htpasswd admin $admin_password


ynh_script_progression "Configuring fail2ban..."
ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-error.log" --failregex='user ".*": password mismatch, client: <HOST>,'

# initialize dist dir
ynh_script_progression "Initializing dist dir..."
mkdir -p $install_dir/lichen-markdown/dist
cd $install_dir/lichen-markdown/src && php cms/build.php
chown -R $app:www-data $install_dir/lichen-markdown/dist

#=================================================
# YJS WEBSOCKET CONFIGURATION
#=================================================
ynh_script_progression "Adding configurations related to yjs-websocket for $app..."

# install node 18 for using yjs websocket 
#nodejs_version=18
#ynh_nodejs_install
#ynh_hide_warnings $nodejs_dir/npm install

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install -g @y/websocket-server
popd


# Create a dedicated systemd config
ynh_config_add_systemd --service=$app-y-websocket --template=y-websocket.service

# add services to ynh
yunohost service add "$app-y-websocket" --needs_exposed_ports="$port_ysocket" --description="lichen-markdown y-websocket service" --log="/var/log/$app/$app-y-websocket.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate /var/log/$app/$app-y-websocket.log

ynh_script_progression "Starting $app-y-websocket systemd services..."

# Start a systemd service
ynh_systemctl --service="$app-y-websocket" --action="start"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
