#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

ynh_config_remove_nginx

ynh_config_remove_phpfpm

#=================================================
# REMOVE YSOCKET CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

#ynh_config_remove_fail2ban

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-y-websocket" >/dev/null; then
    yunohost service remove "$app-y-websocket"
fi

ynh_script_progression "Stopping $app's ywebsocket systemd service..."

# stop systemd service and then remove it 
ynh_systemctl --service="$app-y-websocket" --action="stop"

ynh_config_remove_systemd --service=$app-y-websocket

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
