#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=1G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
upgrade_temp_dir=$install_dir/upgrade
ynh_setup_source --dest_dir="$upgrade_temp_dir"

# upgrade only the lichen-markdown/src/cms folder
mv $install_dir/lichen-markdown/src/cms $upgrade_temp_dir/cms-backup
cp -r $upgrade_temp_dir/lichen-markdown/src/cms $install_dir/lichen-markdown/src/cms
cp $upgrade_temp_dir/lichen-markdown/src/assets/yjs-bundle.iife.js $install_dir/lichen-markdown/src/assets/yjs-bundle.iife.js
ynh_safe_rm $upgrade_temp_dir
chmod -R u+rwX,g+rwX,o= $install_dir/lichen-markdown/
chown -R $app:www-data $install_dir/lichen-markdown/

# reinitialize dist dir
ynh_script_progression "Initializing dist dir..."
mkdir -p $install_dir/lichen-markdown/dist
cd $install_dir/lichen-markdown/src && php cms/build.php
chown -R $app:www-data $install_dir/lichen-markdown/dist

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading PHP-FPM configuration and fail2ban..."

#ynh_script_progression "Configuring fail2ban..."
#ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-error.log" --failregex='user ".*": password mismatch, client: <HOST>,'

# Create a dedicated PHP-FPM config
ynh_app_setting_set_default --key="php_upload_max_filesize" --value="1G"
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# REAPPLY YWEBSOCKET CONFIGURATION
#=================================================
ynh_script_progression "Adding configurations related to yjs-websocket for $app..."

# install node 18 for using yjs websocket 
#nodejs_version=18
#ynh_nodejs_install
#ynh_hide_warnings $nodejs_dir/npm install -g @y/websocket-server

pushd "$install_dir"
	ynh_hide_warnings npm install -g @y/websocket-server
popd

# Create a dedicated systemd config
ynh_config_add_systemd --service=$app-y-websocket --template=y-websocket.service

# add services to ynh
yunohost service add "$app-y-websocket" --needs_exposed_ports="$port_ysocket" --description="lichen-markdown y-websocket service" --log="/var/log/$app/$app-y-websocket.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate /var/log/$app/$app-y-websocket.log

ynh_script_progression "Starting $app-y-websocket systemd services..."

# Start a systemd service
ynh_systemctl --service="$app-y-websocket" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
